name: CI
on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - name: alpine-make-vm-image 
        run: |
          wget https://raw.githubusercontent.com/alpinelinux/alpine-make-vm-image/v0.7.0/alpine-make-vm-image \
              && echo '9803170e07b05b97eb6712e6a9097ad656954d0f  alpine-make-vm-image' | sha1sum -c \
              || exit 1
          mv alpine-make-vm-image /usr/local/bin/
          chmod +x /usr/local/bin/alpine-make-vm-image

      - uses: actions/checkout@v2

      - name: Build image
        run: |
          sudo alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 2G \
              --repositories-file repositories \
              --packages "$(cat packages)" \
              --script-chroot \
              alpine-playground-$(date +%Y-%m-%d).qcow2 -- ./onfigure.sh

      - uses: dev-drprasad/delete-older-releases@v0.2.0
        if: github.event_name != 'pull_request'
        with:
          keep_latest: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: github.event_name != 'pull_request'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Build $(date +%Y-%m-%d)"
          files: |
            alpine-playground-$(date +%Y-%m-%d).qcow2