name: "Build & Release"

on:
  - pull_request
  - push

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - name: alpine-make-vm-image 
        run: |
          version=$(curl --silent https://api.github.com/repos/alpinelinux/alpine-make-vm-image/git/refs/tags | jq -r '.[-1].ref' | awk -F/ '{print $NF}')
          wget https://raw.githubusercontent.com/alpinelinux/alpine-make-vm-image/${version}/alpine-make-vm-image || exit 1
          mv alpine-make-vm-image /usr/local/bin/
          chmod +x /usr/local/bin/alpine-make-vm-image

      - uses: actions/checkout@v4

      - name: Build image
        run: |
          sudo alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 5G \
              --repositories-file repositories \
              --packages "$(cat packages)" \
              --script-chroot \
              alpine-playground.qcow2 -- ./configure.sh

      - name: Bump version and push tag if needed
        id: tag_version
        if: github.event_name == 'push'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false

      - uses: dev-drprasad/delete-older-releases@v0.3.4
        if: ${{ steps.tag_version.outputs.new_tag }}
        with:
          keep_latest: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: softprops/action-gh-release@v1
        if: ${{ steps.tag_version.outputs.new_tag }}
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          files: |
            alpine-playground.qcow2